### PR TITLE
Temporary workaround to #45 (Gzweb not showing model)

### PR DESCRIPTION
**Pull request by 130s**
Only tested on Gzweb. 
Hasn't tested on Gazebo GUI yet.

### CODE REVIEW

**Comment by k-okada** [comment]
gzweb now showing what model? tetris model? or sun model?

**Comment by k-okada** [comment]
screenshot from 2015-11-05 02 28 41

**Comment by 130s** [comment]
gzweb_hakuto_20151104

This looks similar to what's posted on https://github.com/tork-a/hakuto/issues/45#issuecomment-93349856.

**Comment by k-okada** [comment]
So, do you mean this gzweb screenshot is ok? Or not.
Or did I seeing old commit and if I use newer version , I will get different screenshot.

**Comment by 130s** [comment]
> So, do you mean this gzweb screenshot is ok? Or not.

With the latest gzweb (I think 0.1.2), yes I think this is the best we get.

> Or did I seeing old commit and if I use newer version , I will get different screenshot.

As reported in #45, latest commit of hakuto causes an issue to me.

**Comment by k-okada** [comment]
ok,  i look in to this issue and found several things
1) current tetris model is not good, dae uses texture image but tetris.gazebo.xacro override that with gazebo material tag, we need to revert this https://github.com/k-okada/hakuto/commit/72302a082891103d7409980b4b4e3ebce4b3c50c, 

without this change the robot is gray, and it so hard to find them in the moon. I think it would be one option to not to move initial robot location and camera settings until we solve https://bitbucket.org/osrf/gzweb/issues/66/configurable-cameraview-init-pose
screenshot from 2015-11-05 19 42 52,

gzweb does not properly understand light and hightmap texture, so if you turn off the light, the robot seems black and ground seems white, so you can find the robot easily, but that is not a good solution, I think

2) it seems recent gzweb (1.2.0) assuming `../materials/textures/*png` for texture image and if `deploy.sh` suceeded, it generate `*_coearse.dae` file. https://github.com/k-okada/hakuto/commit/820754a813c2f54e41cddfb0b4527eba183567b3, (and we mannualy run ./coarse_meshes.sh) `deploy.sh` also convert all jpg file to png, so we create `asset/tetris` as copy file and `asset/apollo15_landing_site_1000x1000` as symlink, (deploy.sh uses `find` command and that is not follow symbolic link directory as a default)

**Comment by k-okada** [comment]
I have confirmed this works ok on both gazebo and gzweb
screenshot from 2015-11-05 21 46 11
screenshot from 2015-11-05 21 46 24

**Pull request merged**
